#!/usr/bin/env bash


# below are the full ranges for all parameters
# PARS="2,3,4,5,6,7,8,9,10 1.2f,1.4f,1.6f,1.8f,2.0f,2.2f,2.4f,2.6f 2,3,4,5,6 2,3,4,5,6,7,8,9 0.01f,0.05f,0.1f,0.15f,0.2f,0.25f 2000,4000,8000,16000,48000,96000,192000,384000 0.005f,0.01f,0.02f,0.05f,0.1f,0.15f,0.2f,0.25f 10"

PARS="2,3,4,5,6,7,8,9,10,11,12 1.2f,1.4f,1.6f,1.8f,2.0f,2.2f,2.4f,2.6f,2.8f,3.0f 2 0.01f 2000 0.005f 100"

# below are the short parameters, i.e., one value per parameter
#PARS="4 2.0f 3 0.05f 4000 0.01f 1"


gnome-terminal -e "/home/matthias/workspace/SEEPng/install/seep-master/bin/seep-master --query.file /home/matthias/repos/15-MDF-usecase/applications/simple-event-marking-query/build/libs/simple-event-marking-query.jar --baseclass.name Base --master.port 3500 $PARS"

for i in `seq 1 3`;
do
    gnome-terminal -e "/home/matthias/workspace/SEEPng/install/seep-worker/bin/seep-worker --worker.ip 127.0.0.1 --worker.port 350$i --data.port 500$i --master.ip 127.0.0.1 --master.port 3500"
done    

